"""
Adapted from keras example cifar10_cnn.py
Train ResNet-18 on the CIFAR10 small images dataset.

GPU run command with Theano backend (with TensorFlow, the GPU is automatically used):
    THEANO_FLAGS=mode=FAST_RUN,device=gpu,floatX=float32 python cifar10.py
"""
from __future__ import print_function
#from keras.datasets import cifar10
from keras.datasets import mnist
from keras.preprocessing.image import ImageDataGenerator
# 导入工具包
from keras.utils import np_utils
# 回调函数-观察训练过程中网络内部的状态和统计信息
from keras.callbacks import ReduceLROnPlateau, CSVLogger, EarlyStopping

import numpy as np
import resnet

# ReduceLROnPlateau-当评价指标不在提升时，减少学习率
lr_reducer = ReduceLROnPlateau(factor=np.sqrt(0.1), cooldown=0, patience=5, min_lr=0.5e-6)
# EarlyStopping-当监测值不再改善时，该回调函数将中止训练
early_stopper = EarlyStopping(min_delta=0.001, patience=10)
# CSVLogger-将epoch的训练结果保存在CSV文件中，致辞所有可被转换为string的值
csv_logger = CSVLogger('resnet18_cifar10.csv')


batch_size = 24
nb_classes = 10
nb_epoch = 3
# 数据增强
data_augmentation = True

# input image dimensions
img_rows, img_cols = 28, 28
# The CIFAR10 images are RGB.
img_channels = 1

# The data, shuffled and split between train and test sets（数据，重洗、分离在训练与检测集之间）:
#
#     X_train.shape == (50000,32,32,3)
#     y_train.shape == (50000,1)
#

#(X_train, y_train), (X_test, y_test) = cifar10.load_data()
(X_train, y_train), (X_test, y_test) = mnist.load_data()
X_train = np.expand_dims(X_train,axis=3)
y_train = np.expand_dims(y_train,axis=1)
X_test = np.expand_dims(X_test,axis=3)
y_test = np.expand_dims(y_test,axis=1)

# Convert class vectors to binary class matrices.
# to_categorical-将类别向量（从0到nb_calsses的整数向量）映射为二值类别矩阵
# y_train[0:10]
# array([[6],
#        [9],
#        [9],
#        [4],
#        [1],
#        [1],
#        [2],
#        [7],
#        [8],
#        [3]], dtype=uint8)
# Y_train[0:10]
# array([[ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
#        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
#        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
#        [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
#        [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
#        [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
#        [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
#        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
#        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
#        [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.]])


Y_train = np_utils.to_categorical(y_train, nb_classes)
Y_test = np_utils.to_categorical(y_test, nb_classes)

# 将X_train数据转化为浮点型数值
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')

# subtract mean and normalize
# axis=0 压缩行，对各列取均值，m*n 返回 1*n
mean_image = np.mean(X_train, axis=0)
X_train -= mean_image
X_test -= mean_image
# X_train = X_train/128
X_train /= 128.
X_test /= 128.

model = resnet.ResnetBuilder.build_resnet_18((img_channels, img_rows, img_cols), nb_classes)
model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

if not data_augmentation:
    print('Not using data augmentation.')
    model.fit(X_train, Y_train,
              batch_size=batch_size,
              nb_epoch=nb_epoch,
              validation_data=(X_test, Y_test),
              shuffle=True,
              callbacks=[lr_reducer, early_stopper, csv_logger])
else:
    print('Using real-time data augmentation.')
    # This will do preprocessing and realtime data augmentation:
    datagen = ImageDataGenerator(
        featurewise_center=False,  # set input mean to 0 over the dataset
        samplewise_center=False,  # set each sample mean to 0
        featurewise_std_normalization=False,  # divide inputs by std of the dataset
        samplewise_std_normalization=False,  # divide each input by its std
        zca_whitening=False,  # apply ZCA whitening
        rotation_range=0,  # randomly rotate images in the range (degrees, 0 to 180)
        width_shift_range=0.1,  # randomly shift images horizontally (fraction of total width)
        height_shift_range=0.1,  # randomly shift images vertically (fraction of total height)
        horizontal_flip=True,  # randomly flip images
        vertical_flip=False)  # randomly flip images

    # Compute quantities required for featurewise normalization
    # (std, mean, and principal components if ZCA whitening is applied).
    datagen.fit(X_train)

    # Fit the model on the batches generated by datagen.flow().
    model.fit_generator(datagen.flow(X_train, Y_train, batch_size=batch_size),
                        steps_per_epoch=X_train.shape[0] // batch_size,
                        validation_data=(X_test, Y_test),
                        epochs=nb_epoch, verbose=1, max_q_size=100,
                        callbacks=[lr_reducer, early_stopper, csv_logger])
